name: opera-proxy
version: '1.4.2'
summary: Standalone Opera VPN proxies client.
description: |
  Standalone Opera VPN proxies client. Just run it and it'll start plain HTTP proxy server forwarding traffic via proxies of your choice.

confinement: strict
base: core18

parts:
  opera-proxy:
    plugin: go
    source: .
    build-packages:
      - gcc
    override-build:
      make &&
      cp bin/opera-proxy "$SNAPCRAFT_PART_INSTALL"
    stage:
      - opera-proxy

apps:
  opera-proxy:
    command: opera-proxy
    plugs:
      - network
      - network-bind
